services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=oyinkan1
      - POSTGRES_USER=eduforall
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data 
volumes:
 - postgres-data: